<?php
/**
 * The display setup configuration.
 *
 * @package Location_Weather
 */

if ( ! defined( 'ABSPATH' ) ) {
	die;
} // Cannot access directly.

SPLW::createSection(
	'sp_location_weather_generator',
	array(
		'title'  => __( 'Display Settings', 'location-weather' ),
		'icon'   => '<span><svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" height="14px" width="14px" viewBox="0 0 174.239 174.239" style="enable-background:new 0 0 174.239 174.239;"xml:space="preserve"><g><g><path d="M174.239,174.239H96.945V96.945h77.294V174.239z M111.88,159.305h47.425V111.88H111.88V159.305z"/></g><g><path d="M77.294,174.239H0V96.945h77.294V174.239z M14.935,159.305H62.36V111.88H14.935V159.305z"/></g><g><path d="M174.239,77.294H96.945V0h77.294V77.294z M111.88,62.36h47.425V14.935H111.88V62.36z"/></g><g><path d="M77.294,77.294H0V0h77.294V77.294z M14.935,62.36H62.36V14.935H14.935V62.36z"/></g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g></svg></span>',
		'fields' => array(
			array(
				'type'  => 'tabbed',
				'class' => 'lw-display-tabs',
				'tabs'  => array(
					array(
						'title'  => __( 'Basic Preferences', 'location-weather' ),
						'icon'   => '<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="none"><g clip-path="url(#A)" fill="#23282d"><path d="M9.244 11.125c.078-.028.15-.078.2-.147.153-.197.119-.481-.075-.634a3 3 0 0 1-.528-.472 3.07 3.07 0 0 1 .262-4.331c.059-.059.103-.131.122-.212a.45.45 0 0 0-.325-.55 3.63 3.63 0 0 0-1.397-.056c-4.741 1.034-2.875 7.838 1.741 6.403zm6.022-3.797h-1.147a6.11 6.11 0 0 0-1.306-3.162l.819-.819c.269-.269.269-.703 0-.972s-.703-.269-.972 0l-.816.816a6.11 6.11 0 0 0-3.153-1.309V.719c0-.381-.306-.687-.687-.687s-.688.306-.688.688v1.163a6.12 6.12 0 0 0-3.147 1.306l-.834-.834c-.269-.269-.703-.269-.972 0s-.269.703 0 .972l.831.831a6.12 6.12 0 0 0-1.309 3.138H.703c-.381 0-.687.306-.687.688s.306.687.688.687h1.178a6.1 6.1 0 0 0 1.294 3.144l-.834.834c-.269.269-.269.703 0 .972.134.134.309.2.487.2s.353-.066.487-.2l.831-.831a6.14 6.14 0 0 0 3.141 1.322v1.172c0 .381.306.688.688.688s.688-.306.688-.688v-1.159a6.12 6.12 0 0 0 3.159-1.294l.819.819c.134.134.309.2.488.2s.353-.066.488-.2c.269-.269.269-.703 0-.972l-.816-.816c.712-.884 1.188-1.969 1.322-3.156h1.15c.381 0 .688-.306.688-.687a.69.69 0 0 0-.694-.687zM3.219 8c0-2.637 2.144-4.781 4.781-4.781S12.781 5.363 12.781 8 10.638 12.781 8 12.781 3.219 10.638 3.219 8z"/></g><defs><clipPath id="A"><path fill="#fff" d="M0 0h16v16H0z"/></clipPath></defs></svg></span>',
						'fields' => array(
							array(
								'id'         => 'lw-title',
								'type'       => 'switcher',
								'title'      => __( 'Weather Section Title', 'location-weather' ),
								'class'      => 'splw-first-fields',
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-location-address',
								'type'       => 'switcher',
								'title'      => __( 'Location Name', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-date',
								'type'       => 'switcher',
								'title'      => __( 'Current Date', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw_date_format',
								'type'       => 'select',
								'title'      => __( 'Date Format', 'location-weather' ),
								'title_info' => '<div class="lw-info-label">' . __( 'Date Format', 'location-weather' ) . '</div> <div class="lw-short-content">' . __( 'Choose the most common date format for your visitors.', 'location-weather' ) . '</div><div class="info-button"><a class="lw-open-docs" href="https://locationweather.io/docs/how-to-set-the-date-format/" target="_blank">' . __( 'Open Docs', 'location-weather' ) . '</a></div>',
								'options'    => array(
									'M j, Y' => date_i18n( 'M j, Y' ) . ' (M j, Y)',
									'F j, Y' => date_i18n( 'F j, Y' ) . ' (F j, Y)',
									'Y-m-d'  => date_i18n( 'Y-m-d' ) . ' (Y-m-d)',
									'm/d/Y'  => date_i18n( 'm/d/Y' ) . ' (m/d/Y)',
									'd/m/Y'  => date_i18n( 'd/m/Y' ) . ' (d/m/Y)',
									'custom' => __( 'Custom', 'location-weather' ),
								),
								'default'    => 'M j, Y',
								'dependency' => array(
									'lw-date',
									'==',
									'true',
								),
							),
							array(
								'id'         => 'lw_client_date_format',
								'type'       => 'text',
								'class'      => 'lw_client_date_format',
								'title'      => ' ',
								'default'    => 'F j, Y',
								'dependency' => array(
									'lw-date|lw_date_format',
									'==|==',
									'true|custom',
									true,
								),
							),
							array(
								'id'         => 'lw-show-time',
								'type'       => 'switcher',
								'title'      => __( 'Current Time', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-time-format',
								'class'      => 'splw_custom_button_fields',
								'type'       => 'select',
								'title'      => __( 'Time Format', 'location-weather' ),
								'options'    => array(
									'g:i a' => gmdate( 'g:i a', time() ) . ' (g:i a)',
									'g:i A' => gmdate( 'g:i A', time() ) . ' (g:i A)',
									'H:i'   => gmdate( 'H:i', time() ) . ' (H:i)',
								),
								'default'    => 'g:i a',
								'dependency' => array(
									'lw-show-time',
									'==',
									'true',
									true,
								),
							),
							array(
								'id'         => 'lw-utc-time-zone',
								'type'       => 'select',
								'title'      => 'Time Zone',
								'options'    => array(
									''          => __( 'Default (auto-detected)', 'location-weather' ),
									'UTC-12'    => __( 'UTC-12', 'location-weather' ),
									'UTC-11.5'  => __( 'UTC-11:30', 'location-weather' ),
									'UTC-11'    => __( 'UTC-11', 'location-weather' ),
									'UTC-10.5'  => __( 'UTC-10:30', 'location-weather' ),
									'UTC-10'    => __( 'UTC-10', 'location-weather' ),
									'UTC-9.5'   => __( 'UTC-9:30', 'location-weather' ),
									'UTC-9'     => __( 'UTC-9', 'location-weather' ),
									'UTC-8.5'   => __( 'UTC-8:30', 'location-weather' ),
									'UTC-8'     => __( 'UTC-8', 'location-weather' ),
									'UTC-7.5'   => __( 'UTC-7:30', 'location-weather' ),
									'UTC-7'     => __( 'UTC-7', 'location-weather' ),
									'UTC-6.5'   => __( 'UTC-6:30', 'location-weather' ),
									'UTC-6'     => __( 'UTC-6', 'location-weather' ),
									'UTC-5.5'   => __( 'UTC-5:30', 'location-weather' ),
									'UTC-5'     => __( 'UTC-5', 'location-weather' ),
									'UTC-4.5'   => __( 'UTC-4:30', 'location-weather' ),
									'UTC-4'     => __( 'UTC-4', 'location-weather' ),
									'UTC-3.5'   => __( 'UTC-3:5', 'location-weather' ),
									'UTC-3'     => __( 'UTC-3', 'location-weather' ),
									'UTC-2.5'   => __( 'UTC-2:30', 'location-weather' ),
									'UTC-2'     => __( 'UTC-2', 'location-weather' ),
									'UTC-1.5'   => __( 'UTC-1:30', 'location-weather' ),
									'UTC-1'     => __( 'UTC-1', 'location-weather' ),
									'UTC-0.5'   => __( 'UTC-30', 'location-weather' ),
									'UTC+0'     => __( 'UTC+0', 'location-weather' ),
									'UTC+0.5'   => __( 'UTC+0:30', 'location-weather' ),
									'UTC+1'     => __( 'UTC+1', 'location-weather' ),
									'UTC+1.5'   => __( 'UTC+1:30', 'location-weather' ),
									'UTC+2'     => __( 'UTC+2', 'location-weather' ),
									'UTC+2.5'   => __( 'UTC+2:30', 'location-weather' ),
									'UTC+3'     => __( 'UTC+3', 'location-weather' ),
									'UTC+3.5'   => __( 'UTC+3:30', 'location-weather' ),
									'UTC+4'     => __( 'UTC+4', 'location-weather' ),
									'UTC+4.5'   => __( 'UTC+4:30', 'location-weather' ),
									'UTC+5'     => __( 'UTC+5', 'location-weather' ),
									'UTC+5.5'   => __( 'UTC+5:30', 'location-weather' ),
									'UTC+5.75'  => __( 'UTC+5:45', 'location-weather' ),
									'UTC+6'     => __( 'UTC+6', 'location-weather' ),
									'UTC+6.5'   => __( 'UTC+6:30', 'location-weather' ),
									'UTC+7'     => __( 'UTC+7', 'location-weather' ),
									'UTC+7.5'   => __( 'UTC+7:30', 'location-weather' ),
									'UTC+8'     => __( 'UTC+8', 'location-weather' ),
									'UTC+8.5'   => __( 'UTC+8:30', 'location-weather' ),
									'UTC+8.75'  => __( 'UTC+8:45', 'location-weather' ),
									'UTC+9'     => __( 'UTC+9', 'location-weather' ),
									'UTC+9.5'   => __( 'UTC+9:30', 'location-weather' ),
									'UTC+10'    => __( 'UTC+10', 'location-weather' ),
									'UTC+10.5'  => __( 'UTC+10:30', 'location-weather' ),
									'UTC+11'    => __( 'UTC+11', 'location-weather' ),
									'UTC+11.5'  => __( 'UTC+11:30', 'location-weather' ),
									'UTC+12'    => __( 'UTC+12', 'location-weather' ),
									'UTC+12.5'  => __( 'UTC+12:30', 'location-weather' ),
									'UTC+12.75' => __( 'UTC+12:45', 'location-weather' ),
									'UTC+13'    => __( 'UTC+13', 'location-weather' ),
									'UTC+13.5'  => __( 'UTC+13:30', 'location-weather' ),
									'UTC+13.75' => __( 'UTC+13:45', 'location-weather' ),
									'UTC+14'    => __( 'UTC+14', 'location-weather' ),
								),
								'default'    => '',
								'title_info' => '<div class="lw-info-label">' . __( 'Time Zone', 'location-weather' ) . '</div> <div class="lw-short-content">' . __( 'Recommended to use Default (auto-detected). If your location time is incorrect, use this option to adjust it.', 'location-weather' ) . '</div>',
							),
							array(
								'id'         => 'lw-language',
								'type'       => 'select',
								'title'      => __( 'Language', 'location-weather' ),
								'title_info' => '<div class="lw-info-label">' . __( 'OpenWeatherMap Language', 'location-weather' ) . '</div> <div class="lw-short-content">' . __( 'This is the language for the data from OpenWeatherMap, not for this plugin. English is set as default language.', 'location-weather' ) . '</div>',
								'options'    => array(
									'en'    => __( 'English', 'location-weather' ),
									'af'    => __( 'Afrikaans', 'location-weather' ),
									'sq'    => __( 'Albanian', 'location-weather' ), // al for Albanian.
									'ar'    => __( 'Arabic', 'location-weather' ),
									'az'    => __( 'Azerbaijani', 'location-weather' ),
									'bg'    => __( 'Bulgarian', 'location-weather' ),
									'ca'    => __( 'Catalan', 'location-weather' ),
									'cz'    => __( 'Czech', 'location-weather' ),
									'da'    => __( 'Danish', 'location-weather' ),
									'de'    => __( 'German', 'location-weather' ),
									'el'    => __( 'Greek', 'location-weather' ),
									'eu'    => __( 'Basque', 'location-weather' ),
									'fa'    => __( 'Persian (Farsi)', 'location-weather' ),
									'fi'    => __( 'Finnish', 'location-weather' ),
									'fr'    => __( 'French', 'location-weather' ),
									'gl'    => __( 'Galician', 'location-weather' ),
									'he'    => __( 'Hebrew', 'location-weather' ),
									'hi'    => __( 'Hindi', 'location-weather' ),
									'hr'    => __( 'Croatian', 'location-weather' ),
									'hu'    => __( 'Hungarian', 'location-weather' ),
									'id'    => __( 'Indonesian', 'location-weather' ),
									'it'    => __( 'Italian', 'location-weather' ),
									'ja'    => __( 'Japanese', 'location-weather' ),
									'kr'    => __( 'Korean', 'location-weather' ),
									'la'    => __( 'Latvian', 'location-weather' ),
									'lt'    => __( 'Lithuanian', 'location-weather' ),
									'mk'    => __( 'Macedonian', 'location-weather' ),
									'no'    => __( 'Norwegian', 'location-weather' ),
									'nl'    => __( 'Dutch', 'location-weather' ),
									'pl'    => __( 'Polish', 'location-weather' ),
									'pt'    => __( 'Portuguese', 'location-weather' ),
									'pt_br' => __( 'Português Brasil', 'location-weather' ),
									'ro'    => __( 'Romanian', 'location-weather' ),
									'ru'    => __( 'Russian', 'location-weather' ),
									'sv'    => __( 'Swedish', 'location-weather' ), // sv, se for Swedish.
									'sk'    => __( 'Slovak', 'location-weather' ),
									'sl'    => __( 'Slovenian', 'location-weather' ),
									'es'    => __( 'Spanish', 'location-weather' ), // sp, es for spanish lang.
									'sr'    => __( 'Serbian', 'location-weather' ),
									'th'    => __( 'Thai', 'location-weather' ),
									'tr'    => __( 'Turkish', 'location-weather' ),
									'uk'    => __( 'Ukrainian', 'location-weather' ), // ua, uk for Ukrainian lang.
									'vi'    => __( 'Vietnamese', 'location-weather' ),
									'zh_cn' => __( 'Chinese Simplified', 'location-weather' ),
									'zh_tw' => __( 'Chinese Traditional', 'location-weather' ),
									'zu'    => __( 'Zulu', 'location-weather' ),

								),
								'default'    => 'en',
							),
							array(
								'id'         => 'lw-preloader',
								'type'       => 'switcher',
								'title'      => __( 'Preloader', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Enabled', 'location-weather' ),
								'text_off'   => __( 'Disabled', 'location-weather' ),
								'text_width' => 94,
							),
						),
					),
					array(
						'title'  => __( 'Current Weather', 'location-weather' ),
						'icon'   => '<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="none"><g clip-path="url(#A)"><path d="M4.168 7.167c-.144-.023-.289-.034-.435-.034-.813 0-1.593.323-2.168.898S.667 9.387.667 10.2s.323 1.593.898 2.169 1.355.898 2.168.898c.177 0 .346-.07.471-.195s.195-.295.195-.471-.07-.346-.195-.471-.295-.195-.471-.195c-.46 0-.901-.183-1.226-.508S2 10.66 2 10.2s.183-.901.508-1.226.766-.508 1.226-.508a1.7 1.7 0 0 1 .575.108c.165.059.346.051.504-.023s.282-.206.344-.37c.166-.443.464-.824.853-1.094s.851-.414 1.324-.414.935.144 1.324.414.686.651.853 1.094c.066.16.19.29.347.363s.336.083.501.03c.266-.104.556-.132.837-.081a1.73 1.73 0 0 1 1.471 1.842 1.73 1.73 0 0 1-1.732 1.598c-.177 0-.346.07-.471.195s-.195.295-.195.471.07.346.195.471.295.195.471.195a3.06 3.06 0 0 0 2.954-2.233 3.06 3.06 0 0 0-1.363-3.443 3.19 3.19 0 0 0 .143-.925c.002-.782-.271-1.54-.773-2.141s-1.199-1.005-1.969-1.142-1.564.002-2.242.392-1.197 1.007-1.465 1.742a3.7 3.7 0 0 0-2.051 1.649zm5.165-2.501a2 2 0 0 1 2 2c0 .165-.023.329-.067.487-.256-.026-.514-.021-.769.013a3.68 3.68 0 0 0-2.683-1.8c.187-.22.419-.397.682-.518a1.98 1.98 0 0 1 .836-.183zm6 2c0 .177-.07.346-.195.471s-.295.195-.471.195H14c-.177 0-.346-.07-.471-.195s-.195-.295-.195-.471.07-.346.195-.471S13.823 6 14 6h.667c.177 0 .346.07.471.195s.195.295.195.471zm-6-4c-.177 0-.346-.07-.471-.195S8.667 2.177 8.667 2v-.667c0-.177.07-.346.195-.471s.295-.195.471-.195.346.07.471.195.195.295.195.471V2c0 .177-.07.346-.195.471s-.295.195-.471.195zm3.3 1.367c-.132 0-.261-.039-.37-.112s-.195-.177-.245-.299-.064-.256-.038-.385.089-.248.182-.341l.471-.471c.062-.064.135-.114.216-.149s.169-.053.257-.054.176.016.258.05.156.083.219.146.112.137.146.219.05.17.05.258a.67.67 0 0 1-.203.474l-.471.471c-.125.125-.294.195-.471.195zm-7.071-.195l-.471-.471c-.064-.062-.114-.135-.149-.216s-.053-.169-.054-.257.016-.176.05-.258.083-.156.146-.219.137-.112.219-.146.17-.05.258-.05.176.019.257.054.155.086.216.149l.471.471c.064.062.114.135.149.216s.053.169.054.257-.016.176-.05.258-.083.156-.146.219-.137.112-.219.146-.17.05-.258.05-.176-.019-.257-.054-.155-.086-.216-.149zm-.033 10.357l1.529-1.529H6c-.132 0-.261-.039-.37-.112s-.195-.177-.245-.299-.064-.256-.038-.385.089-.248.182-.341l2.667-2.667c.126-.121.294-.189.469-.187s.342.072.466.195.194.291.195.466-.066.343-.187.469l-1.529 1.529h1.057c.132 0 .261.039.37.112s.195.177.245.299.064.256.038.385-.089.248-.182.341l-2.667 2.667c-.126.121-.294.189-.469.187s-.342-.072-.466-.195-.194-.291-.195-.466.066-.343.187-.469z" fill="#23282d"/></g><defs><clipPath id="A"><path fill="#fff" d="M0 0h16v16H0z"/></clipPath></defs></svg></span>',
						'fields' => array(
							array(
								'id'         => 'lw-icon',
								'type'       => 'switcher',
								'title'      => __( 'Weather Condition Icon', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'               => 'weather-current-icon-type',
								'class'            => 'weather-current-icon-type',
								'forecast_preview' => true,
								'type'             => 'select',
								'title'            => __( 'Icon Type', 'location-weather' ),
								'options'          => array(
									'forecast_icon_set_one' => __( 'Animated', 'location-weather' ),
									'forecast_icon_set_two'   => __( 'Static (No-animation) ', 'location-weather' ),
									'forecast_icon_set_three' => __( 'Light (Line) ', 'location-weather' ),
									'forecast_icon_set_four'  => __( 'Fill ', 'location-weather' ),
									'forecast_icon_set_five'  => __( 'Glassmorphism', 'location-weather' ),
								),
								'title_info'       => '<div class="lw-info-label">' . __( 'Icon Type', 'location-weather' ) . '</div> <div class="lw-short-content">' . __( 'Choose a icon type to visually represent various weather conditions in current weather. These icon sets offer a variety of design options for displaying current weather information.', 'location-weather' ) . '</div><div class="info-button"><a class="lw-open-docs" href="https://locationweather.io/docs/how-to-configure-current-weather-icon-type/" target="_blank">' . __( 'Open Docs', 'location-weather' ) . '</a></div>',
								'default'          => 'forecast_icon_set_one',
								'dependency'       => array( 'lw-icon', '==', 'true', true ),
							),
							array(
								'id'         => 'lw-current-icon-color',
								'type'       => 'color',
								'class'      => 'lw-forecast-data-pro',
								'title'      => __( 'Icon Color', 'location-weather' ),
								'default'    => '#fff',
								'dependency' => array( 'lw-icon|weather-current-icon-type', '==|any', 'true|forecast_icon_set_three,forecast_icon_set_four', true ),
							),
							array(
								'id'         => 'lw_current_icon_size',
								'type'       => 'spinner',
								'class'      => 'current-icon-size',
								'title'      => __( 'Icon size', 'location-weather' ),
								'unit'       => __( 'px', 'location-weather' ),
								'max'        => 30000,
								'min'        => 1,
								'default'    => 58,
								'dependency' => array( 'lw-icon', '==', 'true', true ),
							),
							array(
								'id'         => 'lw-temperature',
								'type'       => 'switcher',
								'title'      => __( 'Temperature', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),

							array(
								'id'         => 'lw-high-low-temperature',
								'class'      => 'splw_show_hide',
								'type'       => 'switcher',
								'title'      => __( 'High & Low Temperature', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-real-feel',
								'class'      => 'splw_show_hide',
								'type'       => 'switcher',
								'title'      => __( 'Real Feel', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-short-description',
								'type'       => 'switcher',
								'title'      => __( 'Weather Condition Short Description', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'type'    => 'notice',
								'style'   => 'normal',
								/* translators: %1$s: anchor tag start, %2$s: anchor tag end. */
								'content' => sprintf( __( 'To show more weather details & stylish icons, %1$sUpgrade to Pro!%2$s', 'location-weather' ), '<a class="lw-open-live-demo" href="https://locationweather.io/pricing/?ref=1" target="_blank"><strong>', '</strong></a>' ),
							),
						),
					),
					array(
						'title'  => __( 'Control Additional Data', 'location-weather' ),
						'icon'   => '<span><svg xmlns="http://www.w3.org/2000/svg" width="17" height="16" fill="#23282d"><path d="M13.111 11.345c-.405 0-.752-.347-.752-.752s.347-.752.752-.752h.579c.694 0 1.273-.579 1.273-1.273s-.579-1.273-1.273-1.273c-.405 0-.752-.318-.781-.723-.058-1.071-.926-1.881-1.996-1.881a2.14 2.14 0 0 0-1.186.376.78.78 0 0 1-.434.145c-.058 0-.116 0-.174-.029-.231-.058-.405-.203-.492-.405-.376-.781-1.186-1.273-2.054-1.273A2.27 2.27 0 0 0 4.286 5.79a2.16 2.16 0 0 0 .087.579c.058.231 0 .521-.174.694a.79.79 0 0 1-.55.231h-.145c-.087-.029-.174-.029-.26-.029-.694 0-1.273.579-1.273 1.273s.579 1.273 1.273 1.273h.579c.405 0 .752.347.752.752s-.347.752-.752.752h-.579A2.78 2.78 0 0 1 .467 8.539c0-1.36.984-2.517 2.315-2.749C2.781 3.707 4.489 2 6.572 2c1.186 0 2.257.521 2.98 1.447.434-.174.897-.289 1.36-.289a3.53 3.53 0 0 1 3.414 2.691c1.244.289 2.112 1.418 2.141 2.691a2.78 2.78 0 0 1-2.778 2.778h-.579v.029zm-1.447-1.62a1.46 1.46 0 0 1-.868 1.331v2.141a.58.58 0 0 1-.579.579.58.58 0 0 1-.579-.579v-2.141a1.43 1.43 0 0 1-.868-1.331 1.43 1.43 0 0 1 .868-1.331v-.405a.58.58 0 0 1 .579-.579.58.58 0 0 1 .579.579v.405a1.46 1.46 0 0 1 .868 1.331zm-3.472 1.736a1.46 1.46 0 0 1-.868 1.331v.405a.58.58 0 0 1-.579.579.58.58 0 0 1-.579-.579v-.405a1.43 1.43 0 0 1-.868-1.331 1.43 1.43 0 0 1 .868-1.331V7.989a.58.58 0 0 1 .579-.579.58.58 0 0 1 .579.579v2.141a1.46 1.46 0 0 1 .868 1.331z"/></svg></span>',
						'fields' => array(
							array(
								'id'         => 'lw-pressure',
								'type'       => 'switcher',
								'title'      => __( 'Pressure', 'location-weather' ),
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div>%s',
									__( 'Atmospheric or Air Pressure', 'location-weather' ),
									__( 'Atmospheric or air pressure on the sea level.', 'location-weather' )
								),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-humidity',
								'type'       => 'switcher',
								'title'      => __( 'Humidity', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-wind',
								'type'       => 'switcher',
								'title'      => __( 'Wind', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-precipitation',
								'class'      => 'splw_show_hide',
								'type'       => 'switcher',
								'title'      => __( 'Precipitation', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-clouds',
								'type'       => 'switcher',
								'title'      => __( 'Clouds', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-rain-chance',
								'class'      => 'splw_show_hide',
								'type'       => 'switcher',
								'title'      => __( 'Rain Chance', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-snow',
								'class'      => 'splw_show_hide',
								'type'       => 'switcher',
								'title'      => __( 'Snow', 'location-weather' ),
								'default'    => false,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-wind-gusts',
								'type'       => 'switcher',
								'title'      => __( 'Wind Gust', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-uv-index',
								'class'      => 'splw_show_hide',
								'type'       => 'switcher',
								'title'      => __( 'UV Index', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div> <div class="lw-short-content">%s</div>',
									__( 'UV Index', 'location-weather' ),
									__( 'The UV index measures the strength of UV radiation from the sun, indicating potential risks of sun exposure, with higher values signifying increased risk. It’s used in weather forecasts to guide sun protection measures.', 'location-weather' )
								),
							),
							array(
								'id'         => 'lw-dew-point',
								'class'      => 'splw_show_hide',
								'type'       => 'switcher',
								'title'      => __( 'Dew Point', 'location-weather' ),
								'default'    => false,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div> <div class="lw-short-content">%s</div>',
									__( 'Dew Point', 'location-weather' ),
									__( 'Set weather for specific locations with coordinates to display the Dew Point.', 'location-weather' )
								),
							),
							array(
								'id'         => 'lw-air-quality',
								'class'      => 'splw_show_hide',
								'type'       => 'switcher',
								'title'      => __( 'Air Quality', 'location-weather' ),
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div> <div class="lw-short-content">%s</div>',
									__( 'Air Quality', 'location-weather' ),
									__( 'Set weather for specific locations with coordinates to display the Air Quality.', 'location-weather' )
								),
								'default'    => false,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-visibility',
								'type'       => 'switcher',
								'title'      => __( 'Visibility', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-sunrise-sunset',
								'type'       => 'switcher',
								'title'      => __( 'Sunrise & Sunset Time', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-moonrise-moonset',
								'class'      => 'splw_show_hide',
								'type'       => 'switcher',
								'title'      => __( 'Moonrise & Moonset Time', 'location-weather' ),
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div> <div class="lw-short-content">%s</div>',
									__( 'Moonrise & Moonset Time', 'location-weather' ),
									__( 'Set weather for specific locations with coordinates to display the Moonrise & Moonset Time.', 'location-weather' )
								),
								'default'    => false,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-moon-phase',
								'class'      => 'splw_show_hide',
								'type'       => 'switcher',
								'title'      => __( 'Moon Phase', 'location-weather' ),
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div> <div class="lw-short-content">%s</div>',
									__( 'Moon Phase', 'location-weather' ),
									__( 'Set weather for specific locations with coordinates to display the Moon Phase.', 'location-weather' )
								),
								'default'    => false,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-national-alerts',
								'class'      => 'splw_show_hide',
								'type'       => 'switcher',
								'title'      => __( 'National Weather Alerts', 'location-weather' ),
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div> <div class="lw-short-content">%s</div>',
									__( 'Display National Weather Alerts', 'location-weather' ),
									__( 'Set weather for specific locations with coordinates to display the National Weather Alerts.', 'location-weather' )
								),
								'default'    => false,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'type'    => 'notice',
								'style'   => 'normal',
								/* translators: %1$s: anchor tag start, %$s: anchor tag end. */
								'content' => sprintf( __( 'To gain access to additional weather data, %1$sUpgrade to Pro!%2$s', 'location-weather' ), '<a class="lw-open-live-demo" href="https://locationweather.io/pricing/?ref=1" target="_blank"><strong>', '</strong></a>' ),
							),
						),
					),
					array(
						'title'  => __( 'Additional Data Styles', 'location-weather' ),
						'icon'   => '<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="none"><g clip-path="url(#B)"><mask id="A" maskUnits="userSpaceOnUse" x="0" y="0" width="16" height="16"><path d="M16 0H0V16H16V0Z" fill="#fff"/></mask><g mask="url(#A)"><path d="M15.3 9.2c0 2.2-1.8 3.9-4 3.9H3.2C1.4 13.1 0 11.7 0 10c0-.8.3-1.6.9-2.1.5-.5 1.2-.9 1.9-1 .1-2.3 2-4.2 4.4-4.2.8 0 1.7.3 2.4.7.6.4 1.2 1 1.5 1.7v.1.1l-.1.1-.8.8c-.1.1-.1 0-.2 0C9.7 4.9 8.5 4 7.2 4 5.5 4 4.1 5.4 4.1 7v.4c0 .2 0 .4-.2.6 0 .1-.2.2-.4.2h-.1-.2c-1 0-1.9.8-1.9 1.8s.8 1.8 1.9 1.8h8.1c1.5 0 2.7-1.2 2.7-2.6 0-.4-.1-.7-.2-1v-.1l.1-.1.7-.7h.2c.3.5.5 1.2.5 1.9zm-3.6-.7c0-.7-.5-1.2-1.2-1.2s-1.2.5-1.2 1.2c0 .9-.5 1.6-1.2 2 .3.2.7.3 1.2.3 1.4.1 2.4-1 2.4-2.3z" fill="#23282d"/><path d="M10.1 11.8c-.3.1-.5.1-.8.1s-.5 0-.8-.1h1.6zm5.6-8.4a.85.85 0 0 0-1.3 0l-3.2 3.2c-.1.1-.1.2 0 .3.4.2.8.5 1 1 0 .1.2.1.3 0l3.2-3.2a.85.85 0 0 0 0-1.3zM5.5 7.5c-.2 0-.4-.2-.4-.4s0-1.1.8-1.7c.7-.5 1.7-.6 2.5 0 .2.1.3.4.1.6-.1.1-.4.2-.6 0-.4-.3-1-.3-1.5 0C6 6.4 6 7 6 7.1c0 .2-.2.4-.5.4z" fill="#23282d"/></g></g><defs><clipPath id="B"><path fill="#fff" d="M0 0h16v16H0z"/></clipPath></defs></svg></span>',
						'fields' => array(
							array(
								'id'         => 'weather-additional-data-layout',
								'class'      => 'weather-additional-data-layout',
								'type'       => 'image_select',
								'title'      => __( 'Additional Data Layout', 'location-weather' ),
								'options'    => array(
									'center'               => array(
										'image' => SPLW::include_plugin_url( 'assets/images/additional-data-layout/list-center.svg' ),
										'name'  => __( 'List Center', 'location-weather' ),
									),
									'left'                 => array(
										'image' => SPLW::include_plugin_url( 'assets/images/additional-data-layout/list-left.svg' ),
										'name'  => __( 'List Left', 'location-weather' ),
									),
									'justified'            => array(
										'image' => SPLW::include_plugin_url( 'assets/images/additional-data-layout/list-justified.svg' ),
										'name'  => __( 'List Justified', 'location-weather' ),
									),
									'column-two'           => array(
										'image'    => SPLW::include_plugin_url( 'assets/images/additional-data-layout/list-2-column.svg' ),
										'name'     => __( 'List 2-Column', 'location-weather' ),
										'pro_only' => true,
									),
									'column-two-justified' => array(
										'image'    => SPLW::include_plugin_url( 'assets/images/additional-data-layout/list-2-col-justified.svg' ),
										'name'     => __( '2-Col Justified', 'location-weather' ),
										'pro_only' => true,
									),
									'grid-one'             => array(
										'image'    => SPLW::include_plugin_url( 'assets/images/additional-data-layout/list-2-column-1.svg' ),
										'name'     => __( 'Grid 1', 'location-weather' ),
										'pro_only' => true,
									),
									'grid-two'             => array(
										'image'    => SPLW::include_plugin_url( 'assets/images/additional-data-layout/grid-1.svg' ),
										'name'     => __( 'Grid 2', 'location-weather' ),
										'pro_only' => true,
									),
									'grid-three'           => array(
										'image'    => SPLW::include_plugin_url( 'assets/images/additional-data-layout/grid-2.svg' ),
										'name'     => __( 'Grid 3', 'location-weather' ),
										'pro_only' => true,
									),
									'carousel-simple'      => array(
										'image'    => SPLW::include_plugin_url( 'assets/images/additional-data-layout/carousel-simple.svg' ),
										'name'     => __( 'Carousel Simple', 'location-weather' ),
										'pro_only' => true,
									),
									'carousel-flat'        => array(
										'image'    => SPLW::include_plugin_url( 'assets/images/additional-data-layout/carousel-flat.svg' ),
										'name'     => __( 'Carousel Flat', 'location-weather' ),
										'pro_only' => true,
									),
								),
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div><div class="lw-short-content">%s</div><div class="info-button"><a class="lw-open-docs" href="https://locationweather.io/docs/how-to-set-weather-additional-data-layout/" target="_blank">%s</a><a class="lw-open-live-demo" href="https://locationweather.io/demos/additional-data-layouts/" target="_blank">%s</a></div>',
									__( 'Additional Data Layout', 'location-weather' ),
									__( 'These styles allow you to choose the presentation that best suits your design and provides additional customization options for displaying weather data. See how it works.', 'location-weather' ),
									__( 'Open Docs', 'location-weather' ),
									__( 'Live Demo', 'location-weather' )
								),
								'default'    => 'center',
								'dependency' => array( 'weather-view', '==', 'vertical', true ),
							),
							array(
								'id'         => 'lw-comport-data-position',
								'type'       => 'checkbox',
								'title'      => __( 'Comport Data Position', 'location-weather' ),
								'default'    => false,
								'title_info' => '<div class="lw-img-tag"><img src="' . SPLW::include_plugin_url( 'assets/images/comport-data-position.svg' ) . '" alt="comport-data-position"></div><div class="lw-info-label img">' . __( 'Comport Data Position', 'location-weather' ) . '</div>',
								'dependency' => array( 'weather-view|weather-additional-data-layout', '==|any', 'vertical|justified,left,center', true ),
							),
							array(
								'id'         => 'weather-layout-style',
								'type'       => 'image_select',
								'class'      => 'weather-layout-style',
								'title'      => __( 'Layout Style', 'location-weather' ),
								'options'    => array(
									'clean'   => array(
										'image' => SPLW::include_plugin_url( 'assets/images/layout-style/clean.svg' ),
										'name'  => __( 'Clean', 'location-weather' ),
									),
									'divided' => array(
										'image'    => SPLW::include_plugin_url( 'assets/images/layout-style/divided.svg' ),
										'name'     => __( 'Divided', 'location-weather' ),
										'pro_only' => true,
									),
									'striped' => array(
										'image'    => SPLW::include_plugin_url( 'assets/images/layout-style/striped.svg' ),
										'name'     => __( 'Striped', 'location-weather' ),
										'pro_only' => true,
									),
								),
								'default'    => 'clean',
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div><div class="lw-short-content">%s</div><div class="info-button"><a class="lw-open-docs" href="https://locationweather.io/docs/how-to-configure-weather-additional-data-layout-style/" target="_blank">%s</a></div>',
									__( 'Layout Style', 'location-weather' ),
									__( 'Layout Styles provide different visual presentations for your weather data, allowing you to choose the one that best fits your design preferences.', 'location-weather' ),
									__( 'Open Docs', 'location-weather' )
								),
								'dependency' => array( 'weather-view|weather-additional-data-layout', '==|any', 'vertical|column-two-justified,column-two,justified,left,center', true ),
							),
							array(
								'id'         => 'lw-weather-icons',
								'type'       => 'switcher',
								'class'      => 'show-weather-icons',
								'title'      => __( 'Display Icon', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'weather-icon-type',
								'class'      => 'weather-icon-type',
								'preview'    => true,
								'type'       => 'select',
								'title'      => __( 'Icon Type', 'location-weather' ),
								'options'    => array(
									'icon_set_one'   => __( 'Regular', 'location-weather' ),
									'icon_set_two'   => __( 'Fill', 'location-weather' ),
									'icon_set_three' => __( 'Light', 'location-weather' ),
								),
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div><div class="lw-short-content">%s</div><div class="info-button"><a class="lw-open-docs" href="https://locationweather.io/docs/how-to-choose-weather-additional-data-icon/" target="_blank">%s</a></div>',
									__( 'Icon Type', 'location-weather' ),
									__( 'Choose an icon set of three distinct sets of icons for displaying additional weather data. These icon sets enhance the visual presentation of additional weather data nicely.', 'location-weather' ),
									__( 'Open Docs', 'location-weather' ),
								),
								'default'    => 'icon_set_one',
								'dependency' => array( 'lw-weather-icons', '==', 'true', true ),
							),
							array(
								'id'         => 'lw-icon-color',
								'type'       => 'color',
								'title'      => __( 'Icon Color', 'location-weather' ),
								'default'    => '#fff',
								'dependency' => array( 'lw-weather-icons', '==', 'true', true ),
							),
							array(
								'id'         => 'lw_icon_size',
								'class'      => 'lw_icon_size',
								'type'       => 'spinner',
								'title'      => __( 'Icon size', 'location-weather' ),
								'unit'       => __( 'px', 'location-weather' ),
								'max'        => 30000,
								'min'        => 1,
								'default'    => 16,
								'dependency' => array( 'lw-weather-icons', '==', 'true', true ),

							),
							array(
								'id'              => 'lw_additional-data-space',
								'type'            => 'spacing',
								'class'           => 'lw-additional-data-space-between',
								'title'           => __( 'Space', 'location-weather' ),
								'units'           => array(
									__( 'px', 'location-weather' ),
								),
								'all'             => true,
								'all_title'       => __( 'Vertical', 'location-weather' ),
								'horizontal'      => true,
								'all_icon'        => '<i class="fa fa-arrows-v" aria-hidden="true"></i>',
								'horizontal_icon' => '<i class="fa fa-arrows-h" aria-hidden="true"></i>',
								'default'         => array(
									'all'        => '4',
									'horizontal' => '0',
								),
								'title_info'      => '<div class="lw-img-tag"><img src="' . SPLW::include_plugin_url( 'assets/images/space.webp' ) . '" alt=""></div><div class="lw-info-label img">' . __( 'Space', 'location-weather' ) . '</div>',
								'dependency'      => array( 'weather-view|weather-additional-data-layout', '==|any', 'vertical|column-two-justified,column-two,justified,left,center', true ),
							),
							array(
								'id'      => 'lw_additional-data-border',
								'type'    => 'border',
								'class'   => 'lw-forecast-data-pro',
								'title'   => __( 'Border', 'location-weather' ),
								'all'     => true,
								'radius'  => true,
								'default' => array(
									'all'    => '1',
									'style'  => 'solid',
									'color'  => '#e2e2e2',
									'radius' => '4',
								),
							),
							array(
								'id'         => 'lw-weather-additional-data-margin',
								'type'       => 'spacing',
								'class'      => 'lw-weather-additional-data-margin',
								'title'      => __( 'Margin', 'location-weather' ),
								'units'      => array(
									__( 'px', 'location-weather' ),
								),
								'right'      => false,
								'left'       => false,
								'default'    => array(
									'top'    => '8',
									'bottom' => '3',
								),
								'title_info' => '<div class="lw-img-tag"><img src="' . SPLW::include_plugin_url( 'assets/images/additional-data-area-margin.svg' ) . '" alt="weather-content-padding"></div><div class="lw-info-label img">' . __( 'Additional Data Area Margin', 'location-weather' ) . '</div>',
							),
							array(
								'type'    => 'notice',
								'style'   => 'normal',
								'class'   => 'notice-padding',
								/* translators: %1$s: anchor tag start, %2$s: first anchor tag end,%3$s: second anchor tag start, %4$s: second anchor tag end. */
								'content' => sprintf( __( 'To display weather data in %1$sAdditional Styles%2$s with advanced customizations, %3$sUpgrade to Pro!%4$s', 'location-weather' ), '<a class="lw-open-live-demo" href="https://locationweather.io/demos/additional-data-layouts/" target="_blank"><strong>', '</strong></a>', '<a class="lw-open-live-demo" href="https://locationweather.io/pricing/?ref=1" target="_blank"><strong>', '</strong></a>' ),

							),
							array(
								'id'    => 'lw-carousel-heading',
								'class' => 'carousel-options',
								'type'  => 'subheading',
								'title' => __( 'Weather Additional Data Carousel', 'location-weather' ),
							),
							array(
								'id'         => 'enable-carousel-autoplay',
								'type'       => 'switcher',
								'class'      => 'lw-forecast-data-pro',
								'title'      => __( 'Carousel AutoPlay', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Enabled', 'location-weather' ),
								'text_off'   => __( 'Disabled', 'location-weather' ),
								'text_width' => 94,

							),
							array(
								'id'         => 'carousel-autoplay-speed',
								'type'       => 'spinner',
								'class'      => 'lw-forecast-data-pro ',
								'title'      => __( 'AutoPlay Delay Time', 'location-weather' ),
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div>%s',
									__( 'AutoPlay Delay Time', 'location-weather' ),
									__( 'Set autoplay delay or interval time. The amount of time to delay between automatically cycling a weather item. For example, 1000 milliseconds (ms) equals 1 second.', 'location-weather' )
								),
								'unit'       => __( 'ms', 'location-weather' ),
								'max'        => 30000,
								'min'        => 1,
								'default'    => 3000,
							),
							array(
								'id'         => 'carousel-speed',
								'type'       => 'spinner',
								'class'      => 'lw-forecast-data-pro',
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div>%s',
									__( 'Carousel Speed', 'location-weather' ),
									__( 'Set carousel scrolling speed. For example, 1000 milliseconds (ms) equals 1 second.', 'location-weather' )
								),
								'title'      => __( 'Carousel Speed', 'location-weather' ),
								'unit'       => __( 'ms', 'location-weather' ),
								'max'        => 30000,
								'min'        => 1,
								'default'    => 600,
							),
							array(
								'id'         => 'carousel_onhover',
								'type'       => 'switcher',
								'class'      => 'lw-forecast-data-pro',
								'title'      => __( 'Stop on Hover', 'location-weather' ),
								'text_on'    => __( 'Enabled', 'location-weather' ),
								'text_off'   => __( 'Disabled', 'location-weather' ),
								'text_width' => 94,
								'default'    => false,
							),
							array(
								'id'       => 'lw_carousel-column',
								'class'    => 'lw-forecast-data-pro',
								'type'     => 'spacing',
								'title'    => __( 'Columns', 'location-weather' ),
								'all'      => true,
								'all_icon' => '<i class="fa fa-desktop"></i>',
								'min'      => 1,
								'max'      => 10,
								'unit'     => false,
								'default'  => array(
									'all' => '3',
								),
							),
							array(
								'id'      => 'weather-details-nav-icon',
								'class'   => 'lw-forecast-data-pro nav-icons',
								'type'    => 'button_set',
								'title'   => __( 'Navigation Icon', 'location-weather' ),
								'options' => array(
									'chevron' => '<i class="fas fa-chevron-right"></i>',
									'angle'   => '<i class="fas fa-angle-right"></i>',
									'arrow'   => '<i class="fas fa-arrow-right"></i>',
									'none'    => __( 'Hide', 'location-weather' ),
								),
								'default' => 'none',
							),
							array(
								'id'      => 'weather-details-nav-color',
								'type'    => 'color_group',
								'class'   => 'lw-forecast-data-pro',
								'title'   => __( 'Navigation Color', 'location-weather' ),
								'options' => array(
									'color'      => __( 'Arrow Color', 'location-weather' ),
									'background' => __( 'Hover Color', 'location-weather' ),
								),
								'default' => array(
									'color'      => '#ffffff',
									'background' => '#ffffff',
								),
							),
							array(
								'type'    => 'notice',
								'style'   => 'normal',
								'class'   => 'notice-padding',
								/* translators: %1$s: anchor tag start, %2$s: first anchor tag end,%3$s: second anchor tag start, %4$s: second anchor tag end. */
								'content' => sprintf( __( 'To unlock the %1$sWeather Data Carousel%2$s with flexible options, %3$sUpgrade to Pro!%4$s', 'location-weather' ), '<a class="lw-open-live-demo" href="https://locationweather.io/demos/weather-carousel/" target="_blank">', '</a>', '<a class="lw-open-live-demo" href="https://locationweather.io/pricing/?ref=1" target="_blank"><strong>', '</strong></a>' ),
							),
						),
					),
					array(
						'title'  => __( 'Weather Forecast Data', 'location-weather' ),
						'icon'   => '<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#23282d"><path d="M2.667 11.556h2.074a1.31 1.31 0 0 0 1.197-.764l.639-1.383 1.437 3.748a1.31 1.31 0 0 0 2.421.071l.768-1.671h1.956a.75.75 0 0 0 .649-1.124.75.75 0 0 0-.649-.375h-2.074a1.31 1.31 0 0 0-1.194.765l-.639 1.383-1.441-3.74a1.31 1.31 0 0 0-2.421-.079l-.765 1.672h-1.96a.75.75 0 0 0-.649 1.124.75.75 0 0 0 .649.375zm8.863-7.265a3.73 3.73 0 0 0-6.886 0 2.98 2.98 0 0 0-2.452 3.704.75.75 0 0 0 1.251.348.75.75 0 0 0 .201-.723 1.53 1.53 0 0 1-.023-.676 1.56 1.56 0 0 1 .565-.872c.282-.218.63-.333.987-.325h.017a.75.75 0 0 0 .725-.562c.164-.648.609-1.188 1.213-1.473s1.304-.285 1.908 0 1.049.825 1.213 1.473a.75.75 0 0 0 .725.562h.024a1.5 1.5 0 0 1 1.537 1.874.75.75 0 0 0 .536.914.74.74 0 0 0 .187.024.75.75 0 0 0 .725-.562 2.97 2.97 0 0 0-.037-1.651c-.168-.536-.484-1.013-.912-1.377a2.97 2.97 0 0 0-1.506-.678h.002z"/></svg></span>',
						'fields' => array(
							array(
								'type'    => 'notice',
								'style'   => 'normal',
								'class'   => 'forecast-pro-notice',
								'content' => 'To display advanced <a href="https://locationweather.io/demos/daily-hourly-weather-forecast/" target="_blank">Weather Forecast Data</a> with customizable options, <a class="lw-open-live-demo" href="https://locationweather.io/pricing/?ref=1" target="_blank"><strong>Upgrade to Pro!</strong></a>',
							),
							array(
								'id'         => 'lw-enable-forecast',
								'class'      => 'lw-forecast-data-pro',
								'type'       => 'switcher',
								'title'      => __( 'Enable Weather Forecast', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Enabled', 'location-weather' ),
								'text_off'   => __( 'Disabled', 'location-weather' ),
								'text_width' => 94,
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div><div class="lw-short-content">%s</div>',
									__( 'Enable Weather Forecast', 'location-weather' ),
									__( 'This option allows you to enable or activate weather forecasts, providing users with future weather predictions and enhancing the utility of your weather feature.', 'location-weather' )
								),
							),
							array(
								'id'         => 'lw_forecast_data_sortable',
								'type'       => 'sortable',
								'title'      => __( 'Forecast Data', 'location-weather' ),
								'class'      => 'style_generator_sortable lw-forecast-data-pro',
								'dependency' => array( 'lw-enable-forecast', '==', 'true' ),
								'default'    => array(
									'temperature'   => true,
									'precipitation' => true,
									'rainchance'    => true,
									'wind'          => true,
									'humidity'      => true,
									'pressure'      => true,
									'snow'          => false,
								),
								'fields'     => array(
									array(
										'id'         => 'temperature',
										'type'       => 'switcher',
										'title'      => __( 'Temperature', 'location-weather' ),
										'text_on'    => __( 'Show', 'location-weather' ),
										'text_off'   => __( 'Hide', 'location-weather' ),
										'text_width' => 75,
									),
									array(
										'id'         => 'precipitation',
										'type'       => 'switcher',
										'title'      => __( 'Precipitation', 'location-weather' ),
										'text_on'    => __( 'Show', 'location-weather' ),
										'text_off'   => __( 'Hide', 'location-weather' ),
										'text_width' => 75,
									),
									array(
										'id'         => 'rainchance',
										'type'       => 'switcher',
										'title'      => __( 'Rain Chance', 'location-weather' ),
										'text_on'    => __( 'Show', 'location-weather' ),
										'text_off'   => __( 'Hide', 'location-weather' ),
										'text_width' => 75,
									),
									array(
										'id'         => 'wind',
										'class'      => 'wind_switch',
										'type'       => 'switcher',
										'title'      => __( 'Wind', 'location-weather' ),
										'text_on'    => __( 'Show', 'location-weather' ),
										'text_off'   => __( 'Hide', 'location-weather' ),
										'text_width' => 75,
									),
									array(
										'id'         => 'humidity',
										'class'      => 'humidity_switch',
										'type'       => 'switcher',
										'title'      => __( 'Humidity', 'location-weather' ),
										'text_on'    => __( 'Show', 'location-weather' ),
										'text_off'   => __( 'Hide', 'location-weather' ),
										'text_width' => 75,
									),
									array(
										'id'         => 'pressure',
										'type'       => 'switcher',
										'title'      => __( 'Pressure', 'location-weather' ),
										'text_on'    => __( 'Show', 'location-weather' ),
										'text_off'   => __( 'Hide', 'location-weather' ),
										'text_width' => 75,
									),
									array(
										'id'         => 'snow',
										'type'       => 'switcher',
										'title'      => __( 'Snow', 'location-weather' ),
										'text_on'    => __( 'Show', 'location-weather' ),
										'text_off'   => __( 'Hide', 'location-weather' ),
										'text_width' => 75,
									),
								),
							),
							array(
								'id'         => 'lw-forecast-type',
								'class'      => 'lw-forecast-data-pro',
								'type'       => 'button_set',
								'title'      => __( 'Weather Forecast Type', 'location-weather' ),
								'options'    => array(
									'daily'  => __( 'Daily', 'location-weather' ),
									'hourly' => __( 'Hourly', 'location-weather' ),
									'both'   => __( 'Both', 'location-weather' ),
								),
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div><div class="lw-short-content">%s</div><div class="info-button"><a class="lw-open-docs" href="https://locationweather.io/docs/how-to-configure-weather-forecast-type/" target="_blank">%s</a><a class="lw-open-live-demo" href="https://locationweather.io/demos/daily-hourly-weather-forecast/" target="_blank">%s</a></div>',
									__( 'Weather Forecast Type', 'location-weather' ),
									__( 'The Weather Forecast Type option offers flexibility by allowing you to choose between daily, hourly, or a combination of both formats for displaying weather forecasts.', 'location-weather' ),
									__( 'Open Docs', 'location-weather' ),
									__( 'Live Demo', 'location-weather' )
								),
								'default'    => 'both',
								'dependency' => array( 'lw-enable-forecast', '==', 'true' ),
							),
							array(
								'id'         => 'lw-forecast-day',
								'class'      => 'lw-forecast-data-pro',
								'type'       => 'select',
								'title'      => 'Number of Forecast Days To Show',
								'options'    => array(
									'8' => __( '16 Days', 'location-weather' ),
								),
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div><div class="lw-short-content">%s</div><a class="lw-open-docs" href="https://locationweather.io/docs/docs/how-to-set-the-number-of-forecast-days-to-show/" target="_blank">%s</a>',
									__( 'Forecast Days To Show', 'location-weather' ),
									__( 'Set the number of days you want to show weather forecasts for.', 'location-weather' ),
									__( 'Open Docs', 'location-weather' )
								),
								'default'    => '5',
								'dependency' => array( 'lw-enable-forecast|lw-forecast-type', '==|!=', 'true|hourly' ),
							),
							array(
								'id'         => 'lw-forecast-day-name-length',
								'class'      => 'lw-forecast-data-pro',
								'type'       => 'radio',
								'title'      => __( 'Forecast Days Name Length Type', 'location-weather' ),
								'options'    => array(
									'normal' => __( 'Normal (Sunday)', 'location-weather' ),
									'short'  => __( 'Short (Sun)', 'location-weather' ),
								),
								'default'    => 'normal',
								'dependency' => array( 'lw-enable-forecast|lw-forecast-type', '==|!=', 'true|hourly' ),
							),
							array(
								'id'         => 'forecast-title',
								'class'      => 'lw-forecast-data-pro',
								'type'       => 'text',
								'title'      => __( 'Daily Forecast Title', 'location-weather' ),
								'default'    => __( 'Daily Forecast', 'location-weather' ),
								'dependency' => array( 'lw-enable-forecast|lw-forecast-type', '==|!=', 'true|hourly', true ),
							),
							array(
								'id'         => 'lw-hourly-type',
								'class'      => 'lw-forecast-data-pro',
								'type'       => 'button_set',
								'title'      => __( 'Hourly Forecast Type', 'location-weather' ),
								'options'    => array(
									'one-hour'   => __( '1-Hour', 'location-weather' ),
									'three-hour' => __( '3-Hour', 'location-weather' ),
								),
								'default'    => 'one-hour',
								'dependency' => array( 'lw-enable-forecast|lw-forecast-type', '==|!=', 'true|daily' ),
							),
							array(
								'id'         => 'lw-number-forecast-hours',
								'class'      => 'lw-forecast-data-pro',
								'type'       => 'select',
								'title'      => 'Number of Forecast Hours To Show',
								'options'    => array(
									'8' => __( '48 Hours', 'location-weather' ),
								),
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div><div class="lw-short-content">%s</div><div class="info-button"><a class="lw-open-docs" href="https://locationweather.io/docs/how-to-set-the-number-of-forecast-hours-to-show/" target="_blank">%s</a></div>',
									__( 'Forecast Hours To Show', 'location-weather' ),
									__( 'Set the number of the hours you want to show weather forecasts for.', 'location-weather' ),
									__( 'Open Docs', 'location-weather' )
								),
								'default'    => '8',
								'dependency' => array( 'lw-enable-forecast|lw-forecast-type|lw-hourly-type', '==|!=|==', 'true|daily|one-hour' ),
							),
							array(
								'id'         => 'lw-hourly-time-style',
								'class'      => 'lw-forecast-data-pro',
								'type'       => 'checkbox',
								'title'      => __( 'Display Day/Date With Hour', 'location-weather' ),
								'default'    => false,
								'dependency' => array( 'lw-enable-forecast|lw-forecast-type', '==|!=', 'true|daily' ),
							),
							array(
								'id'         => 'hourly-forecast-title',
								'class'      => 'lw-forecast-data-pro',
								'type'       => 'text',
								'title'      => __( 'Hourly Forecast Title', 'location-weather' ),
								'default'    => __( 'Hourly Forecast', 'location-weather' ),
								'dependency' => array( 'lw-enable-forecast|lw-forecast-type', '==|!=', 'true|daily', true ),
							),
							array(
								'id'               => 'weather-forecast-icon-type',
								'class'            => 'lw-forecast-data-pro',
								'class'            => 'weather-forecast-icon-type',
								'forecast_preview' => true,
								'type'             => 'select',
								'title'            => __( 'Icon Type', 'location-weather' ),
								'options'          => array(
									'forecast_icon_set_one' => __( 'Animated', 'location-weather' ),
									'forecast_icon_set_two'   => __( 'Static (No-animation) ', 'location-weather' ),
									'forecast_icon_set_three' => __( 'Light (Line) ', 'location-weather' ),
									'forecast_icon_set_four'  => __( 'Fill ', 'location-weather' ),
									'forecast_icon_set_five'  => __( 'Glassmorphism', 'location-weather' ),
								),
								'title_info'       => sprintf(
									'<div class="lw-info-label">%s</div><div class="lw-short-content">%s</div><div class="info-button"><a class="lw-open-docs" href="https://locationweather.io/docs/how-to-configure-forecast-data-icon-type/" target="_blank">%s</a></div>',
									__( 'Icon Type', 'location-weather' ),
									__( 'Choose an icon type to visually represent various weather conditions in weather forecasts. These icon sets offer a variety of design options for displaying forecasted weather information.', 'location-weather' ),
									__( 'Open Docs', 'location-weather' )
								),
								'default'          => 'forecast_icon_set_one',
								'dependency'       => array( 'lw-enable-forecast', '==', 'true', true ),
							),
							array(
								'id'      => 'lw-forecast-icon-color',
								'class'   => 'lw-forecast-data-pro',
								'type'    => 'color',
								'title'   => __( 'Icon Color', 'location-weather' ),
								'default' => '#fff',
							),
							array(
								'id'         => 'lw_forecast_icon_size',
								'class'      => 'lw-forecast-data-pro',
								'type'       => 'spinner',
								'class'      => 'forecast-icon-size',
								'title'      => __( 'Icon size', 'location-weather' ),
								'unit'       => __( 'px', 'location-weather' ),
								'max'        => 30000,
								'min'        => 1,
								'default'    => 50,
								'dependency' => array( 'lw-enable-forecast', '==', 'true', true ),
							),
							array(
								'id'         => 'lw-forecast-background-color',
								'type'       => 'color',
								'class'      => 'lw-forecast-data-pro',
								'title'      => __( 'Forecast Data Background', 'location-weather' ),
								'default'    => 'transparent',
								'title_info' => '<div class="lw-img-tag"><img src="' . SPLW::include_plugin_url( 'assets/images/weather-forecast-data-background.webp' ) . '" alt="weather-content-padding"></div><div class="lw-info-label img">' . __( 'Weather Forecast Data Background', 'location-weather' ) . '</div>',
								'dependency' => array( 'weather-template|weather-view', 'any|==', 'template-one,template-two,template-three|vertical', true ),
							),
							array(
								'id'          => 'lw_forecast_toggle_button_style',
								'type'        => 'border',
								'class'       => 'lw_forecast_toggle_button_style lw-forecast-data-pro',
								'title'       => __( 'Forecast Toggle Button', 'location-weather' ),
								'width_title' => __( 'Border Width', 'location-weather' ),
								'all'         => true,
								'background'  => true,
								'active_bg'   => true,
								'default'     => array(
									'all'        => '2',
									'style'      => 'solid',
									'color'      => '#fff',
									'active_bg'  => '#fff',
									'background' => '#EA6A1D',
								),
								'dependency'  => array( 'lw-enable-forecast|lw-forecast-type', '==|==', 'true|both', true ),
							),
							array(
								'id'         => 'lw-forecast-toggle-text-color',
								'type'       => 'color_group',
								'class'      => 'lw-forecast-data-pro',
								'title'      => __( 'Forecast Toggle Button Text', 'location-weather' ),
								'options'    => array(
									'color'      => __( 'Color', 'location-weather' ),
									'background' => __( 'Active Color', 'location-weather' ),
								),
								'default'    => array(
									'color'      => '#ffffff',
									'background' => '#EA6A1D',
								),
								'dependency' => array( 'lw-enable-forecast|lw-forecast-type', '==|==', 'true|both', true ),
							),
							array(
								'id'         => 'lw_forecast_max_height',
								'type'       => 'spinner',
								'class'      => 'forecast-max-height lw-forecast-data-pro',
								'title'      => __( 'Maximum Height', 'location-weather' ),
								'unit'       => __( 'px', 'location-weather' ),
								'max'        => 30000,
								'min'        => 1,
								'default'    => 320,
								'title_info' => '<div class="lw-img-tag"><img src="' . SPLW::include_plugin_url( 'assets/images/forecast-area-maximum-height.svg' ) . '" alt="forecast-area-maximum-height"></div><div class="lw-info-label img">' . __( 'Forecast Area Maximum Height', 'location-weather' ) . '</div>',
								'dependency' => array( 'lw-enable-forecast', '==', 'true', true ),
							),
							array(
								'id'         => 'lw-forecast-data-margin',
								'type'       => 'spacing',
								'class'      => 'lw-forecast-data-margin lw-forecast-data-pro',
								'title'      => __( 'Margin', 'location-weather' ),
								'units'      => array(
									__( 'px', 'location-weather' ),
								),
								'right'      => false,
								'left'       => false,
								'default'    => array(
									'top'    => '0',
									'bottom' => '0',
								),
								'title_info' => '<div class="lw-img-tag"><img src="' . SPLW::include_plugin_url( 'assets/images/forecast-area-margin.svg' ) . '" alt="forecast-area-margin"></div><div class="lw-info-label img">' . __( 'Forecast Area Margin', 'location-weather' ) . '</div>',
							),
							array(
								'id'         => 'lw-temperature-heading',
								'type'       => 'subheading',
								'class'      => 'forecast-carousel-options',
								'title'      => __( 'Weather Forecast Data Carousel', 'location-weather' ),
								'dependency' => array( 'lw-enable-forecast', '==', 'true', true ),
							),
							array(
								'id'         => 'enable-forecast-carousel-autoplay',
								'type'       => 'switcher',
								'class'      => 'lw-forecast-data-pro',
								'title'      => __( 'Carousel AutoPlay', 'location-weather' ),
								'default'    => false,
								'text_on'    => __( 'Enabled', 'location-weather' ),
								'text_off'   => __( 'Disabled', 'location-weather' ),
								'text_width' => 94,
								'dependency' => array( 'lw-enable-forecast', '==', 'true', true ),
							),
							array(
								'id'         => 'forecast-carousel-autoplay-speed',
								'type'       => 'spinner',
								'class'      => 'lw-forecast-data-pro',
								'title'      => __( 'AutoPlay Delay Time', 'location-weather' ),
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div>%s',
									__( 'AutoPlay Delay Time', 'location-weather' ),
									__( 'Set autoplay delay or interval time. The amount of time to delay between automatically cycling a weather item. For example, 1000 milliseconds (ms) equals 1 second.', 'location-weather' )
								),
								'unit'       => __( 'ms', 'location-weather' ),
								'max'        => 30000,
								'min'        => 1,
								'default'    => 3000,
								'dependency' => array( 'lw-enable-forecast', '==', 'true', true ),
							),
							array(
								'id'         => 'forecast-carousel-speed',
								'type'       => 'spinner',
								'class'      => 'lw-forecast-data-pro',
								'title_info' => sprintf(
									'<div class="lw-info-label">%s</div>%s',
									__( 'Carousel Speed', 'location-weather' ),
									__( 'Set carousel scrolling speed. For example, 1000 milliseconds (ms) equals 1 second.', 'location-weather' )
								),
								'title'      => __( 'Carousel Speed', 'location-weather' ),
								'unit'       => __( 'ms', 'location-weather' ),
								'max'        => 30000,
								'min'        => 1,
								'default'    => 600,
								'dependency' => array( 'lw-enable-forecast', '==', 'true', true ),

							),
							array(
								'id'         => 'forecast_carousel_onhover',
								'type'       => 'switcher',
								'class'      => 'lw-forecast-data-pro',
								'title'      => __( 'Stop on Hover', 'location-weather' ),
								'text_on'    => __( 'Enabled', 'location-weather' ),
								'text_off'   => __( 'Disabled', 'location-weather' ),
								'text_width' => 94,
								'default'    => false,
								'dependency' => array( 'lw-enable-forecast', '==', 'true', true ),
							),
							array(
								'id'         => 'enable-forecast-carousel-infinite-loop',
								'type'       => 'switcher',
								'class'      => 'lw-forecast-data-pro',
								'title'      => __( 'Infinite Loop', 'location-weather' ),
								'default'    => false,
								'text_on'    => __( 'Enabled', 'location-weather' ),
								'text_off'   => __( 'Disabled', 'location-weather' ),
								'text_width' => 94,
								'dependency' => array( 'lw-enable-forecast', '==', 'true', true ),
							),
							array(
								'id'         => 'lw_forecast-column',
								'class'      => 'lw_forecast-column lw-forecast-data-pro',
								'type'       => 'spacing',
								'title'      => __( 'Columns', 'location-weather' ),
								'all'        => true,
								'all_icon'   => '<i class="fa fa-desktop"></i>',
								'min'        => 1,
								'max'        => 10,
								'unit'       => false,
								'default'    => array(
									'all' => '3',
								),
								'dependency' => array( 'lw-enable-forecast', '==', 'true', true ),
							),
							array(
								'id'         => 'forecast-nav-icon',
								'class'      => 'lw-forecast-data-pro nav-icons',
								'type'       => 'button_set',
								'title'      => __( 'Navigation Icon', 'location-weather' ),
								'options'    => array(
									'chevron' => '<i class="fas fa-chevron-right"></i>',
									'angle'   => '<i class="fas fa-angle-right"></i>',
									'arrow'   => '<i class="fas fa-arrow-right"></i>',
									'none'    => __( 'Hide', 'location-weather' ),
								),
								'default'    => 'none',
								'dependency' => array( 'lw-enable-forecast', '==', 'true', true ),
							),
							array(
								'id'         => 'forecast-nav-color',
								'type'       => 'color_group',
								'class'      => 'lw-forecast-data-pro',
								'title'      => __( 'Navigation Color', 'location-weather' ),
								'options'    => array(
									'color'      => __( 'Arrow Color', 'location-weather' ),
									'background' => __( 'Hover Color', 'location-weather' ),
								),
								'default'    => array(
									'color'      => '#ffffff',
									'background' => '#ffffff',
								),
								'dependency' => array( 'lw-enable-forecast', '==', 'true', true ),
							),
						),
					),
					array(
						'title'  => __( 'Footer', 'location-weather' ),
						'icon'   => '<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="15" fill="none"><g clip-path="url(#A)" fill="#23282d"><path d="M12.156-.047H3.844C2.231-.047.922 1.184.922 2.692v9.615c0 1.512 1.313 2.739 2.922 2.739h8.312c1.613 0 2.922-1.231 2.922-2.739V2.692c0-1.512-1.312-2.739-2.922-2.739zm1.422 12.354c0 .735-.637 1.333-1.422 1.333H3.844c-.784 0-1.422-.598-1.422-1.333V2.692c0-.735.637-1.333 1.422-1.333h8.312c.784 0 1.422.598 1.422 1.333v9.615zm-2.028-1.432h-7.1c-.416 0-.75.313-.75.703s.334.703.75.703h7.1c.416 0 .75-.313.75-.703s-.334-.703-.75-.703z"/></g><defs><clipPath id="A"><path fill="#fff" d="M0 0h16v15H0z"/></clipPath></defs></svg></span>',
						'fields' => array(
							array(
								'id'         => 'lw-weather-details',
								'type'       => 'switcher',
								'title'      => __( 'Detailed Weather', 'location-weather' ),
								'default'    => false,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-weather-update-time',
								'type'       => 'switcher',
								'title'      => __( 'Data Update Time', 'location-weather' ),
								'default'    => false,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
							),
							array(
								'id'         => 'lw-attribution',
								'type'       => 'switcher',
								'title'      => __( 'Weather Attribution', 'location-weather' ),
								'default'    => true,
								'text_on'    => __( 'Show', 'location-weather' ),
								'text_off'   => __( 'Hide', 'location-weather' ),
								'text_width' => 75,
								'title_info' => sprintf( '<div class="lw-info-label">%s</div><div class="lw-short-content">%s</div> <a class="lw-open-docs" href="https://locationweather.io/docs/how-to-display-weather-attribution/" target="_blank">%s</a>', __( 'Weather Attribution (Copyright)', 'location-weather' ), __( 'You can show the weather attribution or copyright in the weather widget footer area for weather authenticity.', 'location-weather' ), __( 'Open Docs', 'location-weather' ) ),
							),
							array(
								'id'         => 'lw-openweather-links',
								'type'       => 'checkbox',
								'title'      => __( 'Link To OpenWeatherMap', 'location-weather' ),
								'default'    => false,
								'dependency' => array( 'lw-attribution', '==', 'true', true ),
							),
							array(
								'id'      => 'lw-attr-margin',
								'type'    => 'spacing',
								'class'   => 'lw-attr-margin',
								'title'   => __( 'Margin', 'location-weather' ),
								'units'   => array(
									__( 'px', 'location-weather' ),
								),
								'right'   => false,
								'left'    => false,
								'default' => array(
									'top'    => '0',
									'bottom' => '0',
								),
							),
						),
					),
				),
			),
		),
	)
);
